version: '2'

services:
    flask:
        environment:
            - LUPIFY_HTTP_PORT=8080
            - LUPIFY_HTTPS_PORT=8443
        ports:
            - '8080:8080'
            - '8443:8443'
    openldap:
        build:
            context: .
            dockerfile: openldap.dockerfile
        environment:
            - LDAP_TLS_VERIFY_CLIENT=try
        ports:
          - '636:636'
